import test from 'node:test';
import assert from 'node:assert/strict';
import {buildCoachCouncil} from '../src/coach-engine.js';
const bike={id:'plan',name:'Endurance',type:'Ride',durationHours:2,tss:100};
const gym={id:'gym',name:'Upper Body',type:'WeightTraining'};
const build=training=>buildCoachCouncil({daily:{training,nutrition:{calorieTarget:2500,macros:{protein_g:150,carbs_g:300,fat_g:60},foodLog:{totals:{kcal:1000}}}}});
test('rest day only shows nutrition',()=>assert.deepEqual(build({}).coaches.map(c=>c.id),['nutrition']));
test('planned bike and gym show only relevant advisors',()=>{assert.deepEqual(build({planned:[bike]}).coaches.map(c=>c.id),['cycling','nutrition']);assert.deepEqual(build({planned:[gym]}).coaches.map(c=>c.id),['gym','nutrition']);});
test('completion removes preparation and updates food to after activity',()=>{const r=build({planned:[bike],completed:[{...bike,id:'actual',pairedEventId:'plan',calories:1200,tss:125}],matched:[{planned:bike,actualId:'actual'}]});assert.deepEqual(r.coaches.map(c=>c.id),['nutrition']);assert.equal(r.coaches[0].phase,'after');assert.equal(r.reviews.length,1);assert.match(r.reviews[0].actions.join(' '),/125 %/);assert.match(r.coaches[0].actions.join(' '),/1200 kcal/);assert.doesNotMatch(r.coaches[0].actions.join(' '),/Během:/);});
test('completed first ride does not hide separate remaining ride',()=>{const r=build({planned:[bike,{...bike,id:'second',name:'Evening Ride'}],completed:[{...bike,id:'actual',pairedEventId:'plan'}]});assert.equal(r.coaches[0].headline,'Evening Ride');assert.equal(r.reviews.length,1);});
test('unplanned activity gets review without claiming plan adherence',()=>assert.match(build({completed:[{...bike,id:'a'}]}).reviews[0].actions.join(' '),/Bez spárovaného/));
