import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {dashboardPage} from '../src/dashboard.js';
const src=readFileSync(new URL('../src/dashboard-client.js',import.meta.url),'utf8');
test('theme is included in all app sections and remains responsive',async()=>{const html=await dashboardPage().text();assert.match(html,/pulse-grid/);assert.match(html,/max-width:700px/);for(const id of ['overview','training','gym','recovery','nutrition'])assert.match(html,new RegExp('id="'+id+'"'));});
test('sleep and healthspan clearly distinguish available metrics from proprietary age',()=>{assert.match(src,/WHOOP Age · není dostupný/);assert.match(src,/ne recovery skóre/);assert.match(src,/filter\(r=>Number.isFinite\(Date.parse\(r.startTime\)\)\)/);});
test('route chart never invents a route when GPS is absent',()=>{const code=src.slice(src.indexOf('function activityRouteSvg('),src.indexOf('async function openActivityProfile('));const ctx=vm.createContext({Math});vm.runInContext(code,ctx);assert.match(ctx.activityRouteSvg(null),/GPS trasa není dostupná/);const svg=ctx.activityRouteSvg({points:[{v:[50,14]},{v:[50.1,14.1]}]});assert.match(svg,/polyline/);assert.doesNotMatch(svg,/NaN|Infinity/);});
test('new bars have a numeric Y axis and retain zero as a real recorded value',()=>{const code=src.slice(src.indexOf('function experienceBars('),src.indexOf('function renderExperience(')),ctx=vm.createContext({fmt:v=>Math.round(v),esc:String,Math});vm.runInContext(code,ctx);const svg=ctx.experienceBars([{label:'Po',values:[0,4]}],{max:10,colors:['blue','green']});assert.match(svg,/text-anchor="end"/);assert.match(svg,/Po/);assert.match(svg,/fill="green"/);assert.doesNotMatch(svg,/NaN/);});
