import test from 'node:test';
import assert from 'node:assert/strict';
import {googleHealthSummary} from '../src/google-dashboard.js';
import {foodSimilarity} from '../src/personal-foods.js';
import {energyBudget} from '../src/energy-budget.js';
test('energy budget uses all-day active calories without adding bike calories again',()=>{const daily={weight:{current:89},training:{completed:[{calories:1762}]},nutrition:{calorieBreakdown:{weightLossDeficit:300}}},profile={age:30,height:180,sex:'male'};const b=energyBudget(daily,profile,{today:{activeCalories:2000}});assert.equal(b.basal,1870);assert.equal(b.active,2000);assert.equal(b.target,4000);assert.equal(energyBudget(daily,profile,{today:{}}),null);});
test('Google metrics supply HRV and resting HR independently of Intervals',()=>{const make=(data_type,payload)=>({data_type,payload_json:JSON.stringify(payload),sample_time:'2026-09-26',value_numeric:null});const r=googleHealthSummary([make('daily-heart-rate-variability',{dailyHeartRateVariability:{date:{year:2026,month:9,day:26},rmssd:65}}),make('daily-resting-heart-rate',{dailyRestingHeartRate:{beatsPerMinute:47}})],'2026-09-26');assert.equal(r.today.hrv,65);assert.equal(r.today.restingHR,47);assert.equal(r.source,'google-health');});
test('daily activity calories and steps are separate, not added twice',()=>{const r=googleHealthSummary([{data_type:'steps',sample_time:'2026-09-26',value_numeric:1000,payload_json:'{}'},{data_type:'active-energy-burned',sample_time:'2026-09-26',value_numeric:400,payload_json:'{}'}],'2026-09-26');assert.equal(r.today.activeCalories,400);assert.equal(r.today.steps,1000);assert.equal(googleHealthSummary([],'2026-09-26').today.activeCalories,undefined);});
test('food names tolerate Czech accents and a short brand typo',()=>{assert.ok(foodSimilarity('monstert','monster')>.7);assert.ok(foodSimilarity('monste','monster')>.7);assert.equal(foodSimilarity('Nektarínka','nektarinka'),.9);assert.ok(foodSimilarity('banán','monster')<.65);});
