import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const client=fs.readFileSync(new URL('../src/dashboard-client.js',import.meta.url),'utf8'),html=fs.readFileSync(new URL('../src/dashboard.js',import.meta.url),'utf8');
function render(enabled,entries=[]){const node={innerHTML:'',querySelectorAll:()=>[],insertAdjacentHTML(_pos,text){this.innerHTML+=text}},slots=[{id:'breakfast',name:'Snídaně',time:'07:30',share:25},{id:'snack_am',name:'Svačina',time:'10:00',share:10},{id:'lunch',name:'Oběd',time:'12:30',share:30},{id:'snack_pm',name:'Svačina',time:'16:00',share:10},{id:'dinner',name:'Večeře',time:'19:00',share:25}],context={uiText:cs=>cs,$:id=>id==='enteredFood'?node:{value:'2026-09-26'},mealSlots:slots,mealEnabled:enabled,mealEntries:entries,mealDiaryPreview:false,mealEntryRow:e=>e.recipe_title,foodMealSlot:e=>e.slot,state:{daily:{nutrition:{calorieTarget:2400,macros:{protein_g:160,carbs_g:300,fat_g:60}}}},pragueToday:()=> '2026-09-26',longDate:d=>d,num:v=>Number(v)||0,fmt:v=>Math.round(Number(v)),esc:v=>String(v)};vm.createContext(context);const start=client.indexOf('function renderMealDiary()'),end=client.indexOf('async function loadEnteredFood()',start);vm.runInContext(client.slice(start,end)+'renderMealDiary()',context);return node.innerHTML;}
test('three meals redistribute full daily calorie target',()=>{const result=render(['breakfast','lunch','dinner']);const targets=[...result.matchAll(/Cíl (\d+) kcal/g)].map(m=>Number(m[1]));assert.equal(targets.length,3);assert.equal(targets.reduce((a,b)=>a+b,0),2400);});
test('disabled and unassigned meal records stay visible',()=>{assert.match(render(['breakfast'],[{slot:'snack_am',recipe_title:'Saved snack',kcal:120}]),/Ostatní a nezařazené záznamy.*Saved snack/);});
test('assistant calls server-side model and keeps proposals unconfirmed',()=>{assert.doesNotMatch(html,/Schránka trenérů/);assert.match(html,/Změny plánu čekají na tvé potvrzení/);assert.match(client,/\/app\/api\/assistant/);assert.match(client,/Návrh potvrdíš nebo upravíš zprávou/);});
