import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {modelContext} from './helpers/recovery-model.mjs';
const source=readFileSync(new URL('../src/dashboard-client.js',import.meta.url),'utf8');
const ctx=modelContext({dateShift:(d,n)=>{const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10);},appProfile:()=>({age:40}),daywideStrain:()=>null});
vm.runInContext(source.slice(source.indexOf('function nightNeed('),source.indexOf('function correctDataPresentation(')),ctx);
const night={date:'2026-09-27',durationMin:513,timeInBedMin:600,stages:{DEEP:120,REM:120}};
const day=i=>'2026-09-'+String(i).padStart(2,'0');
test('sleep index: duration against need, efficiency from 85 %, stages capped',()=>{assert.equal(ctx.sleepIndex(night),100);assert.equal(ctx.sleepIndex({...night,durationMin:420,timeInBedMin:560}),76);assert.equal(ctx.sleepIndex({...night,timeInBedMin:900}),65);});
test('sleep index without bed time is unavailable; without stages it is rescaled',()=>{assert.equal(ctx.sleepIndex({durationMin:480}),null);assert.equal(ctx.sleepIndex({date:'2026-09-27',durationMin:480,timeInBedMin:540}),100);});
test('recovery requires a personal baseline and today\'s HRV or resting HR',()=>{
  const rows=Array.from({length:20},(_,i)=>({id:day(i+1),hrv:78+(i%5),restingHR:54+(i%3)}));
  assert.equal(ctx.recoveryIndex(rows,night,'2026-09-27').score,null);
  rows.push({id:'2026-09-27',hrv:80,restingHR:55});
  const normal=ctx.recoveryIndex(rows,night,'2026-09-27');
  assert.equal(normal.zone,'green');assert.ok(normal.score>=67&&normal.score<=85,String(normal.score));
  rows.at(-1).hrv=55;rows.at(-1).restingHR=63;
  const bad=ctx.recoveryIndex(rows,{...night,durationMin:300},'2026-09-27');
  assert.equal(bad.zone,'red');assert.ok(bad.score<34);
  assert.equal(ctx.recoveryIndex(rows.slice(0,10).concat(rows.at(-1)),night,'2026-09-27').score,null);
});
