import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {parseNutritionPortion} from '../src/food-label.js';
const src=readFileSync(new URL('../src/dashboard-client.js',import.meta.url),'utf8');
test('daily strain uses all-day energy, not activity HR or TSS',()=>{const code=src.slice(src.indexOf('function daywideStrain('),src.indexOf('function recoverySignals(')),ctx=vm.createContext({Math,Number,String,dateShift:(d,n)=>{const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)},measured:v=>v!=null&&Number.isFinite(Number(v)),googleWellness:()=>Array.from({length:8},(_,i)=>({id:`2026-09-${String(i+20).padStart(2,'0')}`,activeCalories:500}))});vm.runInContext(code,ctx);assert.equal(ctx.daywideStrain('2026-09-27').activeCalories,500);assert.ok(ctx.daywideStrain('2026-09-27').score>0);assert.equal(ctx.daywideStrain('2026-09-28'),null);});
test('meal screenshots use summary totals and not ingredient calories',()=>{const a=parseNutritionPortion('Snídaně\n370 kcal 36,5 g\nKalorie Sacharidy\n33,0 g 9,9 g\nBílkoviny Tuky\nMed\n5 g\n15 kcal');assert.deepEqual(a.values,{calories_100g:370,carbs_100g:36.5,protein_100g:33,fat_100g:9.9});assert.equal(a.name,'Snídaně');const b=parseNutritionPortion('Oběd\nQuesadilla\n714 kcal 82,9 g 50,6 g 18,1 g\nKalorie Sacharidy Bílkoviny Tuky\nSuroviny\nKuřecí prsa 120 g');assert.equal(b.values.calories_100g,714);assert.equal(b.values.protein_100g,50.6);});
test('real OCR screenshot ignores ingredient 100g and protein brand',()=>{const a=parseNutritionPortion('9:52 N 69\n< Snídaně 4\n370 kcal 36,5 g\n\nKalorie Sacharidy\n\n33,0 g 9,9 g\n\nBílkoviny Tuky\nMed 15 kcal\n5 g\nJablko 52 kcal\n100 g\nNatural Whey Protein Mango 59 kcal\nProtein & Co., 15 g');assert.equal(a.values.protein_100g,33);assert.equal(a.values.carbs_100g,36.5);assert.equal(a.ambiguous,false);assert.equal(a.name,'Snídaně');});
