const n=v=>Number.isFinite(Number(v))?Number(v):0;
const txt=v=>String(v||"");
const isBike=x=>/ride|cycling|bike|kolo|endurance|threshold|tempo|vo2/i.test(txt(x?.name)+" "+txt(x?.type));
const isGym=x=>/weight|strength|weights|posil|gym/i.test(txt(x?.name)+" "+txt(x?.type));
const mobility={label:"10min mobilita pro cyklistu: kotník, kyčel, hrudní páteř",url:"https://www.rei.com/learn/expert-advice/cycling-how-to-cross-train.html"};
function sleepFacts(xs=[]){const a=xs.filter(x=>n(x.durationMin)>=180).sort((x,y)=>new Date(y.endTime||y.startTime)-new Date(x.endTime||x.startTime)).slice(0,7);return{last:n(a[0]?.durationMin),avg:a.length?a.reduce((s,x)=>s+n(x.durationMin),0)/a.length:0};}
function rideFuel(h,hard){if(h>=3)return hard?"70–90 g sacharidů/h + 500–750 ml tekutin/h":"60–75 g sacharidů/h + 500–750 ml tekutin/h";if(h>=1.5)return hard?"50–70 g sacharidů/h + 500–750 ml tekutin/h":"30–60 g sacharidů/h + 500–750 ml tekutin/h";if(h>=1)return hard?"30–45 g sacharidů/h podle pocitu":"voda; sacharidy jen při hladu nebo navazující náročné jednotce";return"obvykle stačí voda a běžné jídlo před jízdou";}
function cycling(c){const a=[...(c.training?.planned||[]),...(c.training?.completed||[])],r=a.find(isBike),f=c.fitness||{},low=(c.sleep.last&&c.sleep.last<360)||n(f.tsb)<-25;if(!r)return{id:"cycling",title:"Hlavní trenér · cyklistika",status:"recovery",headline:"Den bez kola = prostor pro adaptaci",actions:["Volno není výpadek plánu: dnes buduješ schopnost absorbovat další cyklistický stimul.","Pokud nejsi bolestivý ani nemocný: 20–40 min klidné chůze v konverzačním tempu.","Potom 10 min: knee-to-wall kotník 2×8/strana, 90/90 kyčle 2×6/strana, otevřená kniha 2×6/strana. Bez protahování do bolesti."],evidence:["Proč: chůze zvyšuje běžný pohyb bez další významné tréninkové únavy; mobilita dává kyčli, kotníku a hrudní páteři pohyb mimo opakovanou pozici na kole.","Toto není povinný trénink. Při výrazné únavě je lepší úplné volno a spánek."],resources:[mobility],confidence:"high"};const h=n(r.durationHours),hard=/threshold|vo2|interval|sweet spot|tempo/i.test(txt(r.name)),fuel=rideFuel(h,hard);return{id:"cycling",title:"Hlavní trenér · cyklistika",status:low?"caution":"ready",headline:txt(r.name)||"Dnešní cyklistika",actions:[low&&hard?"Regenerace je slabá: intervaly změň na Z2 nebo je přesuň; cílem je dlouhodobá konzistence, ne splnění každé položky za cenu únavy.":hard?"Dnešní hlavní stimul je kvalita: rozjeď se, drž předepsané intervaly a mezi nimi opravdu lehce regeneruj.":"Dnešní cíl je aerobní objem: rovnoměrné tempo, žádné spontánní závody do kopce.","Fueling na kolo: "+fuel+".","Po jízdě: do 2–3 h normální jídlo s bílkovinou a sacharidy; přesný deficit řeš až po pokrytí výkonu a regenerace."],evidence:["Proč právě tento typ dne: "+(hard?"intenzita rozvíjí výkon v cílovém pásmu, proto nesmí být znehodnocena nedostatkem paliva nebo zbytečnou únavou z gymu.":"vytrvalostní objem rozvíjí aerobní kapacitu s menší cenou za regeneraci než další intenzita."),"Délka "+Math.round(h*60)+" min · Fitness "+n(f.ctl)+" · Fatigue "+n(f.atl)+" · Form "+n(f.tsb)+"."],confidence:r.name?"high":"medium"};}
function gym(c){const a=[...(c.training?.planned||[]),...(c.training?.completed||[])],g=a.find(isGym),ride=a.find(isBike),hardRide=ride&&/threshold|vo2|interval|sweet spot|tempo/i.test(txt(ride.name)),low=c.sleep.last&&c.sleep.last<360;if(!g)return{id:"gym",title:"Silový trenér · pro kolo",status:"recovery",headline:"Dnes není potřeba náhradní gym",actions:["Síla je nástroj pro lepší přenos síly do pedálu, odolnost tkání a stabilní pozici na kole — ne druhý hlavní sport každý den.","Pokud chceš něco udělat: mobilita a lehká aktivace středu těla, ne trénink do únavy."],evidence:["Proč: progres na kole vzniká z kvalitních cyklistických jednotek a jejich regenerace; náhodný těžký gym by ubíral kvalitu dalšímu klíčovému dni."],resources:[mobility],confidence:"high"};return{id:"gym",title:"Silový trenér · pro kolo",status:low?"caution":"ready",headline:txt(g.name)||"Silový trénink pro cyklistu",actions:[low?"Dnes zkrať trénink: uber jednu pracovní sérii na cvik a nech 2–3 opakování v rezervě.":"Zaměření: silný hip hinge / dřepový vzor, jednostranná stabilita, tahy pro horní záda a střed těla. Cíl je síla a odolnost pro pozici na kole.",hardRide?"Vedle intervalů nechoď do selhání a nenech gym pokazit kvalitu kola. Pokud jsou nohy těžké, dej upper body + core a lower-body jen technicky.":"Když zítra není klíčové kolo, můžeš progresovat: přidej zátěž až po splnění horní hranice opakování při čisté technice a RPE 7–9.","Zapiš váhu, opakování a RPE — bez těchto dat trenér neumí rozlišit opravdový progres od náhodně dobrého dne."],evidence:["Proč právě tento trénink: posilování doplňuje kolo tam, kde kolo samo nedává dostatečný stimul — maximální síla, kostní zatížení, stabilita kyčle a trupu.",hardRide?"Cyklistická kvalita je tento den hlavní. Gym ji podporuje, nesoutěží s ní.":"Bez konfliktu s intenzivní jízdou může gym nést plnohodnotný silový stimul."],confidence:"high"};}
function nutrition(c){const t=n(c.nutrition?.calorieTarget||c.calories?.target),f=c.food||{},m=c.nutrition?.macros||{},protein=n(m.protein_g??m.proteinGrams),carbs=n(m.carbs_g??m.carbsGrams),fat=n(m.fat_g??m.fatGrams),r={k:Math.max(0,t-n(f.kcal)),p:Math.max(0,protein-n(f.protein_g)),c:Math.max(0,carbs-n(f.carbs_g)),f:Math.max(0,fat-n(f.fat_g))},ride=[...(c.training?.planned||[]),...(c.training?.completed||[])].find(isBike),h=n(ride?.durationHours),hard=/threshold|vo2|interval|sweet spot|tempo/i.test(txt(ride?.name));return{id:"nutrition",title:"Sportovní výživa · pro kolo",status:n(f.kcal)?"tracking":"missing-data",headline:n(f.kcal)?"Palivo pro výkon a regeneraci":"Nejdřív potřebujeme dnešní příjem",actions:["Dnešní rámec: "+Math.round(t)+" kcal · protein "+Math.round(protein)+" g · sacharidy "+Math.round(carbs)+" g · tuk "+Math.round(fat)+" g.",ride?"Protože máš "+(hard?"kvalitní":"vytrvalostní")+" kolo ("+Math.round(h*60)+" min), sacharidy nejsou odměna ani selhání diety: část patří před, během a po jízdě. Během: "+rideFuel(h,hard)+".":"Bez kola drž sacharidy spíš podle hladu a další jednotky; protein rozlož do 3–5 jídel, aby regenerace nestála na jednom večerním jídle.","Teď zbývá: "+Math.round(r.k)+" kcal · P "+Math.round(r.p)+" g · C "+Math.round(r.c)+" g · F "+Math.round(r.f)+" g."],evidence:["Proč tyto hodnoty: protein chrání a obnovuje svalovou hmotu při cyklistice i případném deficitu; sacharidy se periodizují podle délky a intenzity kola; tuk je minimální základ, ne hlavní palivo pro intervaly.",ride?"Tréninkové palivo je už součástí denního cíle, proto se nemá odečítat pod záminkou rychlejšího hubnutí.":"Bez evidovaných jídel je to plán, ne skutečné vyhodnocení deficitu."],confidence:n(f.kcal)?"high":"low"};}
export function buildCoachCouncil(input){
  const daily=input.daily||{},training=daily.training||{},completed=training.completed||[],matched=training.matched||[],used=new Set();
  const planned=(training.planned||[]).filter(p=>{
    if(matched.some(m=>String(m.planned?.id)===String(p.id)&&p.id!=null))return false;
    const found=completed.find(a=>!used.has(a.id)&&(p.id!=null&&String(a.pairedEventId||a.plannedEventId)===String(p.id)||txt(p.name).trim()&&txt(p.name).trim().toLowerCase()===txt(a.name).trim().toLowerCase()));
    if(found){used.add(found.id);return false}return true;
  });
  const c={...daily,training:{...training,planned,completed:[]},sleep:sleepFacts(input.sleepSessions||[]),fitness:input.fitness||{},food:daily.nutrition?.foodLog?.totals||{}},coaches=[];
  if(planned.some(isBike))coaches.push({...cycling(c),phase:'before'});
  if(planned.some(isGym))coaches.push({...gym(c),phase:'before'});
  const reviews=completed.filter(a=>isBike(a)||isGym(a)).map(a=>{
    const bike=isBike(a),plan=matched.find(m=>String(m.actualId)===String(a.id))?.planned,h=n(a.durationHours),tss=n(a.tss),loadRatio=plan&&n(plan.tss)>0?tss/n(plan.tss):null,actions=[];
    actions.push('Dokončeno: '+(h>0?Math.round(h*60)+' min · ':'délka není dostupná · ')+(tss>0?Math.round(tss)+' TSS · ':'')+Math.round(n(a.calories))+' kcal evidovaného výdeje.');
    if(loadRatio!=null)actions.push('Zátěž proti plánu: '+Math.round(loadRatio*100)+' % ('+Math.round(tss)+' / '+Math.round(n(plan.tss))+' TSS). '+(loadRatio>1.15?'Zátěž byla vyšší než plán; při další jednotce zohledni skutečnou únavu.':loadRatio<.85?'Zátěž byla nižší než plán. Bez průběhu výkonu a důvodu zkrácení to neznamená nekvalitní trénink.':'Celková zátěž je blízko plánu; sama ale nepotvrzuje správné provedení intervalů.'));
    else actions.push('Bez spárovaného plánu nelze vyhodnotit jeho splnění. Aktivita se přesto započítává do dnešní zátěže a výživy.');
    const np=n(a.payload?.icu_weighted_average_watts),avg=n(a.payload?.average_watts),hr=n(a.payload?.average_heartrate);if(np||avg||hr)actions.push('Naměřeno: '+[np?'NP '+Math.round(np)+' W':'',avg?'průměr '+Math.round(avg)+' W':'',hr?'tep '+Math.round(hr)+' bpm':''].filter(Boolean).join(' · ')+'.');
    if(!bike)actions.push('Pro hodnocení silového progresu jsou potřeba pracovní série, váhy, opakování a RPE v Gymu.');
    return {id:'review-'+a.id,title:bike?'Kolo · hodnocení dokončené jízdy':'Gym · dokončený trénink',headline:txt(a.name)||'Dokončená aktivita',phase:'after',status:'tracking',confidence:'medium',actions,evidence:['Zdroj: dokončená aktivita '+txt(a.source||'z připojených dat')+'.','Jde o datový souhrn, ne analýzu průběhu intervalů. Bez výkonových křivek nelze potvrdit kvalitu jednotlivých bloků.']};
  });
  const fuel=nutrition(c),done=completed.filter(a=>isBike(a)||isGym(a));
  if(done.length){fuel.headline=planned.some(isBike)||planned.some(isGym)?'Po aktivitě · palivo i pro zbývající plán':'Po aktivitě · regenerace a zbývající příjem';fuel.phase='after';fuel.actions[1]='Dnes už máš dokončeno '+done.map(a=>txt(a.name)||txt(a.type)).join(', ')+'. Evidovaný výdej těchto aktivit je '+Math.round(done.reduce((s,a)=>s+n(a.calories),0))+' kcal. Denní cíl zohledňuje dokončené i zbývající plánované aktivity; tento výdej nepřičítej podruhé.';fuel.actions.push('Zapiš i jídlo a nápoje snědené během aktivity. Zbývající makra počítám jen z evidovaného příjmu, ne z domněnky, že už jsi doplnil palivo.');}
  else fuel.phase=planned.length?'before':'rest';
  fuel.analysis=[{label:'Příjem a zbývající energie',text:n(c.food.kcal)?'Zapsáno '+Math.round(n(c.food.kcal))+' z '+Math.round(n(c.nutrition?.calorieTarget))+' kcal. Zbývá '+Math.round(Math.max(0,n(c.nutrition?.calorieTarget)-n(c.food.kcal)))+' kcal. Nezapsaná jídla nelze započítat.':'Příjem zatím není evidovaný. Doporučení vychází z denního cíle, nikoli z měřeného energetického deficitu.'},{label:'Návaznost na trénink',text:done.length?'Do denního příjmu započítej také tyčinky, gely a nápoje z aktivity. Dokončený výdej již patří do denního cíle.':planned.some(isBike)?'Palivo během jízdy je část denního příjmu. Rozlož zbývající sacharidy mezi jídlo před jízdou, samotnou jízdu a následující jídlo.':'Rozlož protein mezi vybraná jídla. Bez evidovaného tréninku nelze odůvodnit závodní dávkování sacharidů.'}];
  for(const coach of coaches){coach.analysis=coach.analysis||[{label:'Plán a provedení',text:coach.id==='cycling'?'Cílem je dodržet strukturu předepsané jednotky, nejen dosáhnout TSS. Délka ani název nepotvrzují cílové watty; rozhodující je intervalový předpis.':'Zapisuj každou pracovní sérii, zátěž, opakování a rezervu. Teprve srovnání stejných cviků umožňuje odlišit progres od změny programu.'},{label:'Kontext připravenosti',text:'Poslední dostupný spánek: '+(c.sleep.last?Math.round(c.sleep.last)+' min':'není dostupný')+'. Fitness / Fatigue / Form: '+[c.fitness.ctl,c.fitness.atl,c.fitness.tsb].map(v=>v==null?'nedostupné':Math.round(n(v))).join(' / ')+'. Tyto souhrny nenahrazují aktuální pocit únavy.'}];}
  for(const review of reviews){const a=completed.find(x=>'review-'+x.id===review.id),p=a.payload||{},plan=matched.find(m=>String(m.actualId)===String(a.id))?.planned,np=n(p.icu_normalized_watts||p.icu_weighted_average_watts),avg=n(p.average_watts),ftp=n(p.icu_ftp);review.analysis=[{label:'Délka proti plánu',text:plan&&n(plan.durationHours)>0?Math.round(n(a.durationHours)*60)+' / '+Math.round(n(plan.durationHours)*60)+' minut ('+Math.round(n(a.durationHours)/n(plan.durationHours)*100)+' %). Samotná délka neříká, zda byly splněny pracovní bloky.':'Srovnatelný plán není dostupný.'},{label:'Intenzita a rovnoměrnost',text:np&&ftp?'IF '+(np/ftp).toFixed(2)+' z naměřeného NP '+Math.round(np)+' W a FTP '+Math.round(ftp)+' W.'+(avg?' Variabilita NP / průměr: '+(np/avg).toFixed(2)+'.':''): 'NP a FTP nejsou společně dostupné; intenzitu neodhaduji jako naměřenou hodnotu z pouhého TSS.'}];}
  coaches.push(fuel);
  for(const coach of coaches)coach.evidence=coach.evidence?.map(text=>text.replace(/(Fitness|Fatigue|Form) (-?\d+(?:\.\d+)?)/g,(_,label,value)=>({Fitness:'Kondice',Fatigue:'Únava',Form:'Forma'}[label])+' '+Number(Number(value).toFixed(1))));
  return {version:'adaptive-coach-council-v3',generatedAt:new Date().toISOString(),priorities:coaches.map(c=>c.headline+': '+c.actions[0]),coaches,reviews,guardrails:['Poradce se mění podle dnešních zbývajících plánů a dokončených aktivit, ne podle zítřejšího plánu.','Dokončení se projeví po synchronizaci zdroje a obnovení dat aplikace.','Chybějící délka, intervaly nebo záznam jídla nejsou nula ani důkaz splnění.']};
}
