// Provider credentials per user, AES-GCM encrypted with a key derived from STRENGTH_API_KEY.
async function table(env){await env.DB.prepare('CREATE TABLE IF NOT EXISTS connection_credentials (user_id INTEGER NOT NULL, provider TEXT NOT NULL, encrypted TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY (user_id, provider))').run();}
async function key(env){if(!env.STRENGTH_API_KEY)throw new Error('Chybí zabezpečení propojení.');const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(env.STRENGTH_API_KEY));return crypto.subtle.importKey('raw',hash,'AES-GCM',false,['encrypt','decrypt']);}
const enc=bytes=>btoa(String.fromCharCode(...new Uint8Array(bytes)));
const dec=text=>Uint8Array.from(atob(text),c=>c.charCodeAt(0));
function userId(env){const id=Number(env.USER_ID);if(!Number.isInteger(id)||id<=0)throw new Error('Připojení vyžaduje přihlášeného uživatele.');return id;}
export async function saveConnectionSecret(env,provider,value){const uid=userId(env);await table(env);const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(env),new TextEncoder().encode(value));await env.DB.prepare('INSERT INTO connection_credentials(user_id,provider,encrypted,updated_at) VALUES (?,?,?,?) ON CONFLICT(user_id,provider) DO UPDATE SET encrypted=excluded.encrypted,updated_at=excluded.updated_at').bind(uid,provider,enc(iv)+'.'+enc(cipher),new Date().toISOString()).run();}
export async function deleteConnectionSecret(env,provider){const uid=userId(env);await table(env);await env.DB.prepare('DELETE FROM connection_credentials WHERE user_id=? AND provider=?').bind(uid,provider).run();}
// Loads the signed-in user's credentials into env. Only the owner falls back to
// the legacy global secrets; userEnv() already removed them for everyone else.
export async function connectionEnvironment(env){if(!env.DB||!env.STRENGTH_API_KEY||!env.USER_ID)return env;await table(env);const result=await env.DB.prepare('SELECT provider,encrypted FROM connection_credentials WHERE user_id=?').bind(userId(env)).all();const resolved={...env,CONNECTED_PROVIDERS:[]};for(const row of result.results||[]){const [iv,cipher]=row.encrypted.split('.');const plain=new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:dec(iv)},await key(env),dec(cipher)));if(row.provider==='google')resolved.GOOGLE_REFRESH_TOKEN=plain;if(row.provider==='intervals')resolved.INTERVALS_API_KEY=plain;if(row.provider==='google_scopes')resolved.GOOGLE_SCOPES=plain.split(/\s+/).filter(Boolean);}if(resolved.GOOGLE_REFRESH_TOKEN)resolved.CONNECTED_PROVIDERS.push('google');if(resolved.INTERVALS_API_KEY)resolved.CONNECTED_PROVIDERS.push('intervals');return resolved;}
// Dashboard data needs both required sources connected.
export const REQUIRED_PROVIDERS=['google','intervals'];
export function missingProviders(env){const connected=env.CONNECTED_PROVIDERS||[];return REQUIRED_PROVIDERS.filter(p=>!connected.includes(p));}
