function renderHealth(){const w=state.weight||{};$("hWeight").textContent=fmt(w.latest?.value_numeric,1);$("hAvg7").textContent=fmt(w.average7d,1);$("hAvg30").textContent=fmt(w.average30d,1);$("hActivities").textContent=state.activities?.count||0;const wr=(w.records||[]).slice(-365);chartSvg("healthWeightChart",wr.map(x=>num(x.value_numeric)),[],wr.map(x=>dateLabel(String(x.sample_time).slice(0,10))));const acts=(state.activities?.activities||[]).slice(0,30);$("healthActivityTable").innerHTML=acts.length?'<div class="scroll"><table><thead><tr><th>Datum</th><th>Aktivita</th><th>Typ</th><th>Zdroj</th></tr></thead><tbody>'+acts.map(x=>{let p={};try{p=JSON.parse(x.payload_json||"{}")}catch{}const e=p.exercise||{};return '<tr><td>'+esc(String(x.start_time||"").slice(0,16).replace("T"," "))+'</td><td>'+esc(p.name||p.title||e.displayName||e.exerciseType||"Activity")+'</td><td>'+esc(p.type||p.category||e.exerciseType||"")+'</td><td>'+esc(x.source_family==="intervals"?"Intervals.icu":"Google Health")+'</td></tr>'}).join("")+'</tbody></table></div>':'<div class="muted">Žádné aktivity.</div>'}
function renderGym(){const values=state.gym?.values||[];const rows=values.slice(7).filter(r=>r.some(v=>String(v??"").trim()!==""));$("gymMeta").textContent=(values[2]?.[1]||"Dnešní silový trénink")+" · "+pragueToday();$("gymNotice").textContent=rows.length?rows.filter(r=>String(r[0]||"")==="WORK").length+" pracovních řádků · změny se zapisují zpět do Google Sheets":"Dnešní sheet je prázdný. Můžeš vygenerovat plán.";const start=values.slice(7).findIndex(r=>r.some(v=>String(v??"").trim()!==""));const actualRows=start<0?[]:values.slice(7+start);$("gymRows").innerHTML=actualRows.map((r,i)=>{const idx=i+(start<0?0:start),type=r[0]||"",exercise=r[1]||"";const rawVideo=state.gym?.videoLinks?.[idx+7]||r[10]||"";const formula=String(rawVideo);const formulaUrl=formula.match(/HYPERLINK\(\s*"([^"]+)"/i)?.[1]||"";const video=/^https?:\/\//i.test(formula)?formula:formulaUrl||("https://www.youtube.com/results?search_query="+encodeURIComponent(String(exercise||"")+" exercise technique"));return '<tr data-row="'+idx+'"><td><span class="gym-type">'+esc(type)+'</span></td><td><strong>'+esc(exercise)+'</strong></td><td>'+esc(r[2]||"")+'</td><td>'+esc(r[3]||"")+'</td><td>'+esc(r[4]||"")+'</td><td><input data-col="5" value="'+esc(r[5]||"")+'" inputmode="decimal"></td><td><input data-col="6" value="'+esc(r[6]||"")+'" inputmode="numeric"></td><td><input data-col="7" value="'+esc(r[7]||"")+'" inputmode="decimal"></td><td><input data-col="8" type="checkbox" '+(String(r[8]).toUpperCase()==="TRUE"||r[8]===true?"checked":"")+'></td><td><a href="'+esc(video)+'" target="_blank" rel="noopener noreferrer">▶ Video</a></td></tr>'}).join("")||'<tr><td colspan="10" class="muted">Žádný plán.</td></tr>'}
async function loadGym(){state.gym=await jsonFetch("/app/api/gym");renderGym()}
async function saveGym(){const b=$("saveGym");b.disabled=true;b.textContent="Saving…";try{const values=(state.gym?.values||[]).map(r=>Array.isArray(r)?r.slice():[]);const rows=document.querySelectorAll("#gymRows tr[data-row]");rows.forEach(tr=>{const idx=Number(tr.dataset.row)+7;if(!values[idx])values[idx]=[];tr.querySelectorAll("input[data-col]").forEach(inp=>{const c=Number(inp.dataset.col);values[idx][c]=inp.type==="checkbox"?(inp.checked?"TRUE":"FALSE"):inp.value})});const used=values.slice(7);while(used.length&&used[used.length-1].every(v=>String(v??"").trim()===""))used.pop();const result=await jsonFetch("/app/api/gym",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({values:used})});toast(result.sheetSaved?"Workout uložen · historie zapsána":"Workout uložen do historie · Google Sheets není dostupný");await loadGym()}catch(e){toast("Save selhal: "+e.message)}finally{b.disabled=false;b.textContent="Save workout"}}
async function generateGym(){const b=$("generateGym");b.disabled=true;b.textContent="Generating…";try{await jsonFetch("/app/api/gym/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date:pragueToday()})});toast("Today's plan generated");await loadGym()}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent="Generate today's plan"}}
window.addEventListener("error",e=>{try{toast("Chyba aplikace: "+(e.error?.message||e.message||"neznámá chyba"))}catch{}});
window.addEventListener("unhandledrejection",e=>{try{toast("Chyba aplikace: "+(e.reason?.message||String(e.reason||"Promise rejected")))}catch{}});
async function load(){ $("topStatus").textContent="Načítám…"; const end=dateShift(weekStart,6); const jobs=[["daily","/app/api/daily"],["fitness","/app/api/fitness?days=90"],["week","/app/api/week?start="+weekStart],["weight","/app/api/weight"],["activities","/app/api/activities"],["nutrition","/app/api/nutrition?start="+weekStart+"&end="+dateShift(end,1)],["sleep","/app/api/sleep?start="+dateShift(pragueToday(),-365)+"&end="+dateShift(pragueToday(),1)],["healthDb","/app/api/health-db"],["gym","/app/api/gym"]]; const results=await Promise.allSettled(jobs.map(([,url])=>jsonFetch(url))); state={...state}; let failed=0; results.forEach((r,i)=>{const key=jobs[i][0]; if(r.status==="fulfilled") state[key]=r.value; else {failed++; state[key]={status:"error",message:r.reason?.message||"Načtení selhalo"};}}); try{renderOverview();}catch{} try{renderTraining();}catch{} try{renderNutrition();}catch{} try{renderRecovery();}catch{} try{renderHealth();}catch{} try{renderGym();}catch{} $("topStatus").textContent=failed===0?"Live · "+new Date().toLocaleTimeString("cs-CZ"):(failed<jobs.length?"Částečně načteno":"Data unavailable"); $("topStatus").className=failed===0?"status-label small":failed<jobs.length?"status-label small status-partial":"status-label small status-error"; if(failed) toast("Některá datová služba není dostupná.");}
document.querySelectorAll(".navbtn").forEach(b=>b.onclick=()=>activate(b.dataset.view));
$("refresh").onclick=async()=>{const b=$("refresh");b.disabled=true;b.textContent="Syncing…";try{const r=await jsonFetch("/app/api/sync",{method:"POST"});toast(r.status==="accepted"?"Synchronizace běží na pozadí. Kontroluji nová data…":"Data synchronized");let n=0;const poll=()=>{n++;b.textContent=n<4?"Syncing…":"Refreshing…";load();if(n<4)setTimeout(poll,4500);else{b.disabled=false;b.textContent="Refresh"}};setTimeout(poll,3000)}catch(e){toast("Sync selhal: "+e.message);b.disabled=false;b.textContent="Refresh"}};
$("prevWeek").onclick=()=>{weekStart=dateShift(weekStart,-7);selectedHistoryDate=weekStart;load()};
$("nextWeek").onclick=()=>{weekStart=dateShift(weekStart,7);selectedHistoryDate=weekStart;load()};
$("thisWeek").onclick=()=>{weekStart=pragueMonday();selectedHistoryDate=weekStart;load()};
$("saveGym").onclick=saveGym;$("generateGym").onclick=generateGym;
$("sleepRange").onchange=renderRecovery;
load();function renderHealth(){
  const w=state.weight||{};$("hWeight").textContent=fmt(w.latest?.value_numeric,1);$("hAvg7").textContent=fmt(w.average7d,1);$("hAvg30").textContent=fmt(w.average30d,1);$("hActivities").textContent=state.activities?.count||0;
  const wr=(w.records||[]).slice(-365);chartSvg("healthWeightChart",wr.map(x=>num(x.value_numeric)),[],wr.map(x=>dateLabel(String(x.sample_time).slice(0,10))),{W:760,H:300});
  const acts=(state.activities?.activities||[]).slice(0,50);$("healthActivityTable").innerHTML=acts.length?'<div class="scroll"><table><thead><tr><th>Datum</th><th>Aktivita</th><th>Typ</th><th>Zdroj</th></tr></thead><tbody>'+acts.map(x=>{let p={};try{p=JSON.parse(x.payload_json||"{}")}catch{}const e=p.exercise||{};return '<tr><td>'+esc(String(x.start_time||"").slice(0,16).replace("T"," "))+'</td><td>'+esc(p.name||p.title||e.displayName||e.exerciseType||"Activity")+'</td><td>'+esc(p.type||p.category||e.exerciseType||"")+'</td><td>'+esc(x.source_family==="intervals"?"Intervals.icu":"Google Health")+'</td></tr>'}).join("")+'</tbody></table></div>':'<div class="muted">Žádné aktivity.</div>';
  const db=state.healthDb?.groups||[];$("healthDataSummary").innerHTML=db.length?'<div class="scroll"><table><thead><tr><th>Zdroj</th><th>Typ</th><th>Role</th><th>Záznamů</th></tr></thead><tbody>'+db.map(x=>'<tr><td>'+esc(x.source_family||"")+'</td><td>'+esc(x.data_type||"")+'</td><td>'+esc(x.record_role||"")+'</td><td>'+fmt(x.count)+'</td></tr>').join("")+'</tbody></table></div>':'<div class="muted">Historie zdrojových dat zatím není dostupná.</div>';
}
function renderGym(){
  const values=state.gym?.values||[],rows=values.slice(7).filter(r=>r.some(v=>String(v??"").trim()!==""));$("gymMeta").textContent=(values[2]?.[1]||"Dnešní silový trénink")+" · "+pragueToday();$("gymNotice").textContent=rows.length?rows.filter(r=>String(r[0]||"")==="WORK").length+" pracovních řádků · změny se zapisují zpět do Google Sheets":"Dnešní sheet je prázdný. Můžeš vygenerovat plán.";
  const start=values.slice(7).findIndex(r=>r.some(v=>String(v??"").trim()!=="")),actualRows=start<0?[]:values.slice(7+start);
  $("gymRows").innerHTML=actualRows.map((r,i)=>{const idx=i+(start<0?0:start),type=r[0]||"",exercise=r[1]||"",rawVideo=state.gym?.videoLinks?.[idx+7]||r[10]||"",formula=String(rawVideo),formulaUrl=formula.match(/HYPERLINK\(\s*"([^"]+)"/i)?.[1]||"",video=/^https?:\/\//i.test(formula)?formula:formulaUrl||("https://www.youtube.com/results?search_query="+encodeURIComponent(String(exercise||"")+" exercise technique"));return '<tr data-row="'+idx+'"><td><span class="gym-type">'+esc(type)+'</span></td><td><strong>'+esc(exercise)+'</strong></td><td>'+esc(r[2]||"")+'</td><td>'+esc(r[3]||"")+'</td><td>'+esc(r[4]||"")+'</td><td><input data-col="5" value="'+esc(r[5]||"")+'" inputmode="decimal"></td><td><input data-col="6" value="'+esc(r[6]||"")+'" inputmode="numeric"></td><td><input data-col="7" value="'+esc(r[7]||"")+'" inputmode="decimal"></td><td><input data-col="8" type="checkbox" '+(String(r[8]).toUpperCase()==="TRUE"||r[8]===true?"checked":"")+'></td><td><a href="'+esc(video)+'" target="_blank" rel="noopener noreferrer">▶ Video</a></td></tr>'}).join("")||'<tr><td colspan="10" class="muted">Žádný plán.</td></tr>';
  const history=state.gym?.history||[],groups={};history.forEach(x=>(groups[x.workout_date]??=[]).push(x));const dates=Object.keys(groups).sort().reverse();
  $("gymHistory").innerHTML=dates.length?dates.map(date=>'<div class="history-workout"><strong>'+esc(date)+'</strong><div class="history-sets">'+groups[date].map(x=>'<div class="history-set">'+esc(x.exercise)+' · '+fmt(x.actual_kg,1)+' kg × '+fmt(x.actual_reps,0)+(Number.isFinite(Number(x.rpe))?' · RPE '+fmt(x.rpe,1):"")+'</div>').join("")+'</div></div>').join(""):'<div class="muted">Historie zatím není zapsaná.</div>';
}
