// Where an exercise should be felt, and what should not hurt or work instead
// (the "procítění" of the technique card). One pair per catalog exercise; a
// new catalog exercise needs its pair too (see tests/exercise-technique).
export const FEEL = {
  "DB bench press": ["Hlavně prsní svaly – nejvíc dole v protažení a při tlaku k sobě nad hrudníkem; přední ramena a triceps pomáhají.", "Píchání v rameni znamená lokty moc do stran nebo uvolněné lopatky."],
  "Low row": ["Střed zad mezi lopatkami a široký sval zádový; na konci lopatky stáhni k sobě.", "Biceps jen drží – když tahá hlavně ruka, mysli na tah lokty dozadu."],
  "DB shoulder press": ["Přední a boční část ramen, v horní části i triceps.", "Bedra se neprohýbají; zpevni břicho a hýždě."],
  "Pivot leg press": ["Přední stehna a hýždě, nejvíc ve spodní části pohybu.", "Kolena ani spodní záda nebolí; když se pánev dole odlepuje, zmenši hloubku."],
  "Prone leg curl Prime": ["Zadní stehna, nejvíc při plném pokrčení k hýždím.", "Bedra nezvedej; křeč v lýtku znamená natažené špičky – přitáhni je k sobě."],
  "Cable curl": ["Biceps po celou dobu – kladka drží napětí nahoře i dole.", "Lokty zůstávají u boků; když se zapojují ramena, uber váhu."],
  "DB curl": ["Biceps, nejvíc ve střední části a při vytočení dlaně nahoru.", "Záda ani ramena nepracují – žádné švihání trupem."],
  "Hammer curl": ["Vnější strana paže (brachialis) a předloktí.", "Zápěstí rovné, palec nahoře; ramena se nehýbou."],
  "Cable triceps extension": ["Triceps, nejvíc v plném propnutí dole.", "Lokty u těla a na místě; ramena ani předloktí nebolí."],
  "Abs bench crunch": ["Přímý sval břišní, hlavně horní část při zkulacení trupu.", "Krk netahej rukama – tlak má být v břiše, ne v krku."],
  "Chest flat press Prime": ["Prsní svaly při tlaku i protažení, triceps v horní části.", "Lopatky zůstávají stažené; ramena nejdou dopředu k uším."],
  "Shoulder press Prime": ["Přední a boční ramena, triceps v horní části.", "Záda opřená celou plochou, bez prohnutí v bedrech."],
  "Lat pulldown": ["Široký sval zádový – boky zad pod pažemi, když táhneš lokty dolů k bokům.", "Biceps a předloktí jen drží; nezakláněj se ke kladce."],
  "Standing rowing machine": ["Střed zad a široký sval zádový, na konci stažené lopatky.", "Spodní záda nebolí – trup drž pevně a hrudník opřený."],
  "Pendulum squat": ["Přední stehna, ve spodní pozici i hýždě.", "Kolena jdou ve směru špiček a nebolí; paty zůstávají na plotně."],
  "Leg extension Prime": ["Přední stehna, nejvíc v plném propnutí nahoře – chvilku tam vydrž.", "Koleno bez píchání; nehoupej se, pohyb je jen z kolene."],
  "Hip thrust": ["Hýždě, nejvíc nahoře při plném propnutí kyčlí.", "Spodní záda nepracují – brada ke hrudi, žebra dolů; stehna jen pomáhají."],
  "DB Romanian deadlift": ["Zadní stehna a hýždě – protažení zadní strany stehen při předklonu.", "Když cítíš spodní záda, posuň boky víc dozadu a drž záda rovná."],
  "Barbell Romanian deadlift": ["Zadní stehna a hýždě, střed těla pevně drží.", "Osa jede těsně u nohou; tah ve spodních zádech znamená kulatá záda."],
  "DB Bulgarian split squat": ["Přední stehno a hýždě přední nohy; zadní noha jen balancuje.", "Koleno přední nohy nebolí a nepadá dovnitř."],
  "Adduction machine": ["Vnitřní strana stehen, nejvíc při stažení nohou k sobě.", "Zpátky pomalu, bez odrazu z krajní polohy."],
  "Abduction machine": ["Vnější strana hýždí a stehen (střední hýžďový sval).", "Trup se nehoupe; tlak jde jen z kyčlí."],
  "Pec deck": ["Prsní svaly, nejvíc při stažení paží k sobě před hrudníkem.", "Ramena nejdou dopředu a nebolí; lokty lehce pokrčené."],
  "Rear delt pec deck": ["Zadní ramena a horní záda.", "Netahej ramena k uším; pohyb vede loket, ne ruka."],
  "Cable lateral raise": ["Boční část ramene, nejvíc v horní polovině pohybu.", "Trapéz se nezvedá; vedeš loket do strany, ne dlaň nahoru."],
  "Cable pullover": ["Široký sval zádový a zadní strana paže při tahu shora k bokům.", "Lokty jen lehce pokrčené; břicho pevné, záda neprohýbat."],
  "Cable rear delt fly": ["Zadní ramena; konec pohybu cítíš mezi lopatkami.", "Ramena dolů od uší, bez švihu trupem."],
  "Pallof press": ["Šikmé břišní svaly a hluboký střed těla – odporuješ rotaci.", "Trup ani pánev se nestáčí ke kladce; dýchej klidně."],
  "Cable woodchop": ["Šikmé břišní svaly při rotaci trupu, ruce jen drží lano.", "Rotace jde z hrudníku a boků, ne ze spodních zad."],
  "Roman chair": ["Spodní záda a hýždě, při propnutí i zadní stehna.", "Nahoře nepřeprohýbej – zastav v rovině s nohama."],
  "Standing calf raise": ["Lýtka, nejvíc nahoře na špičkách a v protažení dole.", "Kolena klidná a téměř propnutá; bez pérování."],
  "Cable crunch": ["Přímý sval břišní – zkulacuješ trup, žebra k pánvi.", "Pohyb nejde ze sklopení boků ani z rukou."],
  "Barbell bench press": ["Prsní svaly, přední ramena a triceps.", "Lopatky stažené a ramena dole; bolest v rameni = lokty moc do stran nebo osa vysoko na hrudníku."],
  "DB incline press": ["Horní část prsních svalů pod klíční kostí a přední ramena.", "Lavice ne strměji než 30–45°, jinak pracují hlavně ramena."],
  "One-arm DB row": ["Široký sval zádový a střed zad na straně tahu.", "Trup se netočí; táhneš loket k boku, ne ruku k rameni."],
  "Standing multi flight": ["Boční ramena při upažení.", "Trapézy nezvedej; nahoře jen do výšky ramen."],
  "Face pull": ["Zadní ramena a horní záda, na konci vytočení paží ven.", "Krk a trapézy uvolněné; lano k obličeji, lokty vysoko."],
  "Cable overhead triceps extension": ["Dlouhá hlava tricepsu – protažení za hlavou a propnutí vpřed.", "Lokty míří dopředu a nehýbou se; bedra neprohýbej."],
  "Goblet squat": ["Přední stehna a hýždě, střed těla drží jednoručku.", "Kolena ve směru špiček, paty na zemi, záda rovná."],
  "Cable glute kickback": ["Velký sval hýžďový při zanožení – nahoře krátce stiskni.", "Bedra se neprohýbají; noha nejde výš, než dovolí hýždě."],
  "Cable pull-through": ["Hýždě a zadní stehna – boky dozadu, pak silné propnutí kyčlí.", "Táhneš boky, ne rukama; záda rovná."],
  "Cable hip abduction": ["Střední hýžďový sval na boku pracující nohy.", "Trup vzpřímený, pohyb malý a pod kontrolou."],
  "Barbell hip thrust": ["Hýždě, nejvíc nahoře – vteřinu tam vydrž.", "Bedra ani stehna nepřebírají práci; nahoře holeně svisle."],
  "DB reverse lunge": ["Hýždě a stehno přední nohy.", "Koleno přední nohy stabilní; lehký předklon trupu dá víc hýždí."],
  "DB step-up": ["Hýždě a stehno nohy na lavici – vytlač se přes patu.", "Neodrážej se spodní nohou; koleno nepadá dovnitř."],
  "DB single-leg Romanian deadlift": ["Hýždě a zadní stehno stojné nohy, kotník stabilizuje.", "Pánev drž rovně, nestáčej ji ven; záda rovná."],
  "DB sumo squat": ["Vnitřní stehna a hýždě.", "Kolena tlač ven nad špičky; trup vzpřímený."],
  "Leg press high feet": ["Hýždě a zadní stehna – chodidla vysoko, tlak přes paty.", "Bedra zůstávají na opěrce; dolů jen tak hluboko, jak pánev drží."],
  "Abduction machine forward lean": ["Horní a střední část hýždí v předklonu.", "Předklon s rovnými zády; tlak z kyčlí, ne trupem."],
  "Glute hyperextension": ["Hýždě a zadní stehna – tlak z kyčlí, záda lehce zakulacená.", "Bedra nepracují; nahoře nepřeprohýbej."],
  "Cable fly": ["Prsní svaly, nejvíc při stažení rukou k sobě.", "Lokty lehce pokrčené po celou dobu; ramena nejdou dopředu."],
  "Low-to-high cable fly": ["Horní část prsních svalů – pohyb zdola šikmo nahoru.", "Ramena dole, ruce nahoře jen do výšky brady."],
  "Single-arm cable row": ["Široký sval zádový a střed zad pracující strany.", "Trup se nestáčí; loket vedeš k boku."],
  "Close-grip lat pulldown": ["Spodní část širokého svalu zádového, lokty k bokům.", "Nezakláněj se; biceps jen pomáhá."],
  "Wide-grip low row": ["Horní záda a zadní ramena – lokty široko.", "Trapézy nezvedej k uším; konec pohybu cítíš mezi lopatkami."],
  "Barbell row": ["Střed zad, široký sval zádový a zadní ramena.", "Spodní záda drží neutrálně a nebolí; trup se během série nezvedá."],
  "DB lateral raise": ["Boční ramena; jednoručky vedeš lokty do stran.", "Trapézy se nezvedají; nahoře jen do výšky ramen."],
  "DB Arnold press": ["Přední a boční ramena, při rotaci i zadní část.", "Záda opřená, bez prohnutí v bedrech."],
  "DB rear delt fly": ["Zadní ramena a horní záda.", "Ramena od uší; lehká váha a čisté provedení."],
  "DB incline curl": ["Biceps v protažení – paže visí za tělem.", "Ramena zůstávají na opěrce, lokty nejdou dopředu."],
  "Cable rope hammer curl": ["Vnější strana paže (brachialis) a předloktí.", "Lokty u těla, zápěstí rovně."],
  "Cable triceps kickback": ["Triceps v plném propnutí za tělem.", "Nadloktí nehybné a souběžně s trupem."],
  "DB overhead triceps extension": ["Dlouhá hlava tricepsu – protažení za hlavou.", "Lokty míří nahoru a k sobě; břicho pevné, bez prohnutí."],
  "Single-leg calf raise": ["Lýtko stojné nohy v celém rozsahu.", "Pomalu dolů do protažení; kotník neuhýbá do stran."],
  "Barbell back squat": ["Přední stehna, hýždě a střed těla.", "Kolena ve směru špiček, záda neutrální; bolest v kolenou nebo zádech = zastav a uber."],
  "Barbell front squat": ["Hlavně přední stehna, horní záda drží osu.", "Lokty vysoko, trup vzpřímený; zápěstí osu jen přidržují."],
  "Smith machine squat": ["Přední stehna a hýždě podle postavení nohou.", "Kolena ani bedra nebolí; chodidla trochu před tělem."],
  "Smith machine split squat": ["Hýždě a stehno přední nohy.", "Koleno nepadá dovnitř; zadní noha jen balancuje."],
  "Smith machine hip thrust": ["Hýždě, nahoře výdrž.", "Žebra dolů, bez prohnutí beder."],
  "Smith machine incline press": ["Horní část prsních svalů a přední ramena.", "Lopatky stažené; osa klesá k horní části hrudníku."],
  "Barbell overhead press": ["Ramena, triceps a střed těla.", "Hýždě a břicho zpevněné, bez záklonu v bedrech."],
  "DB wrist curl": ["Flexory na vnitřní straně předloktí.", "Pohyb jen v zápěstí; předloktí leží na lavici."],
  "DB reverse wrist curl": ["Extenzory na vnější straně předloktí.", "Lehká váha; bolest u lokte = uber nebo zkrať rozsah."],
  "Cable reverse curl": ["Brachioradialis a vnější strana předloktí.", "Lokty u těla, zápěstí rovně."],
  "DB shrug": ["Horní trapézy – ramena nahoru k uším, nahoře výdrž.", "Rameny nerotuj; krk uvolněný."],
  "Barbell shrug": ["Horní trapézy.", "Paže rovně, netáhni rukama; rameny nerotuj."],
  "Smith machine shrug": ["Horní trapézy.", "Ramena rovně nahoru a dolů; hlava v prodloužení páteře."],
  "Cable upright row": ["Trapézy a boční ramena.", "Lokty nejvýš do výšky ramen; píchání v rameni = zastav níž nebo širší úchop."],
  "Barbell good morning": ["Zadní stehna a hýždě; spodní záda drží neutrální páteř.", "Záda nikdy nekulať; začni lehce a jdi jen do pocitu protažení zadních stehen."]
};
