// English "feel" pairs for every exercise in exercise-feel.js (same keys): where the
// exercise should be felt, and what should not hurt or take over instead.
export const FEEL_EN = {
  "Push-up": ["Chest and triceps as you push up.", "No shoulder or wrist pain; keep your torso braced."],
  "Bodyweight squat": ["Quads and glutes.", "Knees track over your toes; the movement must not hurt."],
  "Glute bridge": ["Glutes as you lift your hips.", "Don't overarch your lower back; the movement must not hurt."],
  "Dead bug": ["Your abs hold your torso steady.", "Your lower back stays on the mat and doesn't hurt."],
  "DB bench press": ["Mainly your chest – most at the bottom stretch and as you press in over your chest; front delts and triceps assist.", "A sharp pain in your shoulder means your elbows are flared too wide or your shoulder blades have relaxed."],
  "Low row": ["Mid-back between your shoulder blades and your lats; squeeze your shoulder blades together at the end.", "Your biceps only hold on – if your arms are doing most of the pulling, think about driving your elbows back."],
  "DB shoulder press": ["Front and side delts, plus triceps at the top.", "Don't arch your lower back; brace your abs and glutes."],
  "Pivot leg press": ["Quads and glutes, most at the bottom of the movement.", "No knee or lower-back pain; if your hips lift at the bottom, reduce the depth."],
  "Prone leg curl Prime": ["Hamstrings, most when fully curled toward your glutes.", "Don't lift your lower back; a calf cramp means your toes are pointed – pull them toward you."],
  "Cable curl": ["Biceps throughout – the cable keeps tension at the top and bottom.", "Elbows stay at your sides; if your shoulders join in, reduce the weight."],
  "DB curl": ["Biceps, most in the middle of the rep and as you turn your palm up.", "Your back and shoulders don't work – no swinging your torso."],
  "Hammer curl": ["Outer upper arm (brachialis) and forearm.", "Wrists straight, thumbs up; shoulders don't move."],
  "Cable triceps extension": ["Triceps, most at full lockout at the bottom.", "Elbows tucked and fixed; no shoulder or forearm pain."],
  "Abs bench crunch": ["Rectus abdominis, mainly the upper part as you curl your torso.", "Don't pull on your neck with your hands – the pressure should be in your abs, not your neck."],
  "Chest flat press Prime": ["Chest during the press and the stretch, triceps at the top.", "Shoulder blades stay pulled back; shoulders don't roll forward toward your ears."],
  "Shoulder press Prime": ["Front and side delts, triceps at the top.", "Whole back flat against the backrest, no arch in your lower back."],
  "Lat pulldown": ["Lats – the sides of your back under your arms as you drive your elbows down to your sides.", "Biceps and forearms only hold on; don't lean back toward the pulley."],
  "Standing rowing machine": ["Mid-back and lats, shoulder blades squeezed at the end.", "No lower-back pain – keep your torso solid and your chest on the pad."],
  "Pendulum squat": ["Quads, plus glutes at the bottom.", "Knees track over your toes and don't hurt; heels stay on the platform."],
  "Leg extension Prime": ["Quads, most at full extension at the top – hold it there for a moment.", "No sharp knee pain; don't swing – the movement comes only from the knee."],
  "Hip thrust": ["Glutes, most at the top with your hips fully extended.", "Your lower back doesn't work – chin to chest, ribs down; your thighs only assist."],
  "DB Romanian deadlift": ["Hamstrings and glutes – a stretch along the back of your thighs as you hinge.", "If you feel your lower back, push your hips farther back and keep your back flat."],
  "Barbell Romanian deadlift": ["Hamstrings and glutes, with your core holding firm.", "The bar travels close to your legs; a pull in your lower back means your back is rounding."],
  "DB Bulgarian split squat": ["Front-leg quad and glute; the back leg only balances.", "Front knee doesn't hurt or cave in."],
  "Adduction machine": ["Inner thighs, most as you squeeze your legs together.", "Return slowly, no bouncing out of the end position."],
  "Abduction machine": ["Outer glutes and thighs (glute medius).", "Your torso doesn't rock; the push comes only from your hips."],
  "Pec deck": ["Chest, most as you bring your arms together in front of you.", "Shoulders don't roll forward or hurt; elbows slightly bent."],
  "Rear delt pec deck": ["Rear delts and upper back.", "Don't shrug toward your ears; lead with your elbow, not your hand."],
  "Cable lateral raise": ["Side delt, most in the top half of the movement.", "Traps don't lift; drive your elbow out to the side, not your palm up."],
  "Cable pullover": ["Lats and the back of your upper arm as you pull from overhead down to your hips.", "Elbows only slightly bent; abs tight, don't arch your back."],
  "Cable rear delt fly": ["Rear delts; you feel the end of the movement between your shoulder blades.", "Shoulders down away from your ears, no swinging your torso."],
  "Pallof press": ["Obliques and deep core – you're resisting rotation.", "Torso and hips don't turn toward the pulley; breathe calmly."],
  "Cable woodchop": ["Obliques as your torso rotates; your hands just hold the handle.", "Rotation comes from your chest and hips, not your lower back."],
  "Roman chair": ["Lower back and glutes, plus hamstrings as you extend.", "Don't overarch at the top – stop in line with your legs."],
  "Standing calf raise": ["Calves, most at the top on your toes and in the stretch at the bottom.", "Knees still and nearly straight; no bouncing."],
  "Cable crunch": ["Rectus abdominis – you're curling your torso, ribs toward your pelvis.", "The movement doesn't come from bending at the hips or from your arms."],
  "Barbell bench press": ["Chest, front delts and triceps.", "Shoulder blades squeezed and shoulders down; shoulder pain = elbows flared too wide or the bar too high on your chest."],
  "DB incline press": ["Upper chest below the collarbone and front delts.", "Bench no steeper than 30–45°, or your shoulders do most of the work."],
  "One-arm DB row": ["Lats and mid-back on the pulling side.", "Torso doesn't rotate; drive your elbow to your hip, not your hand to your shoulder."],
  "Standing multi flight": ["Side delts as you raise your arms out.", "Don't shrug your traps; go only up to shoulder height."],
  "Face pull": ["Rear delts and upper back, with your arms rotating out at the end.", "Neck and traps relaxed; rope to your face, elbows high."],
  "Cable overhead triceps extension": ["Long head of the triceps – stretch behind your head and lockout in front.", "Elbows point forward and stay still; don't arch your lower back."],
  "Goblet squat": ["Quads and glutes, with your core holding the dumbbell.", "Knees over your toes, heels on the floor, back flat."],
  "Cable glute kickback": ["Glute max as you kick back – squeeze briefly at the top.", "Lower back doesn't arch; your leg goes only as high as your glutes allow."],
  "Cable pull-through": ["Glutes and hamstrings – hips back, then a strong hip extension.", "Pull with your hips, not your arms; back flat."],
  "Cable hip abduction": ["Glute medius on the side of the working leg.", "Torso upright, movement small and controlled."],
  "Barbell hip thrust": ["Glutes, most at the top – hold for a second.", "Lower back and thighs don't take over; shins vertical at the top."],
  "DB reverse lunge": ["Glutes and front-leg quad.", "Front knee stable; a slight forward lean of your torso puts more on your glutes."],
  "DB step-up": ["Glute and quad of the leg on the bench – drive through your heel.", "Don't push off with your bottom leg; knee doesn't cave in."],
  "DB single-leg Romanian deadlift": ["Glute and hamstring of the standing leg, with your ankle stabilizing.", "Keep your hips square, don't let them open out; back flat."],
  "DB sumo squat": ["Inner thighs and glutes.", "Push your knees out over your toes; torso upright."],
  "Leg press high feet": ["Glutes and hamstrings – feet high, push through your heels.", "Lower back stays on the pad; go only as deep as your hips stay down."],
  "Abduction machine forward lean": ["Upper and middle glutes in the forward lean.", "Lean forward with a flat back; push from your hips, not your torso."],
  "Glute hyperextension": ["Glutes and hamstrings – drive from your hips, upper back slightly rounded.", "Your lower back doesn't work; don't overarch at the top."],
  "Cable fly": ["Chest, most as you bring your hands together.", "Elbows slightly bent throughout; shoulders don't roll forward."],
  "Low-to-high cable fly": ["Upper chest – the movement goes diagonally from low to high.", "Shoulders down, hands only up to chin height."],
  "Single-arm cable row": ["Lats and mid-back on the working side.", "Torso doesn't rotate; drive your elbow to your hip."],
  "Close-grip lat pulldown": ["Lower lats, elbows to your sides.", "Don't lean back; your biceps only assist."],
  "Wide-grip low row": ["Upper back and rear delts – elbows wide.", "Don't shrug your traps toward your ears; you feel the end of the movement between your shoulder blades."],
  "Barbell row": ["Mid-back, lats and rear delts.", "Lower back holds neutral and doesn't hurt; your torso doesn't rise during the set."],
  "DB lateral raise": ["Side delts; lead the dumbbells out to the sides with your elbows.", "Traps don't lift; go only up to shoulder height."],
  "DB Arnold press": ["Front and side delts, plus rear delts during the rotation.", "Back against the pad, no arch in your lower back."],
  "DB rear delt fly": ["Rear delts and upper back.", "Shoulders away from your ears; light weight and clean form."],
  "DB incline curl": ["Biceps in the stretch – your arms hang behind your body.", "Shoulders stay on the backrest; elbows don't move forward."],
  "Cable rope hammer curl": ["Outer upper arm (brachialis) and forearm.", "Elbows at your sides, wrists straight."],
  "Cable triceps kickback": ["Triceps at full lockout behind you.", "Upper arm still and parallel to your torso."],
  "DB overhead triceps extension": ["Long head of the triceps – stretch behind your head.", "Elbows point up and in; abs tight, no arching."],
  "Single-leg calf raise": ["Calf of the standing leg through the full range.", "Lower slowly into the stretch; your ankle doesn't roll to the sides."],
  "Barbell back squat": ["Quads, glutes and core.", "Knees over your toes, back neutral; knee or back pain = stop and reduce the weight."],
  "Barbell front squat": ["Mainly quads, with your upper back holding the bar.", "Elbows high, torso upright; your wrists only steady the bar."],
  "Smith machine squat": ["Quads and glutes, depending on your foot position.", "No knee or lower-back pain; feet slightly in front of your body."],
  "Smith machine split squat": ["Glutes and front-leg quad.", "Knee doesn't cave in; the back leg only balances."],
  "Smith machine hip thrust": ["Glutes, with a hold at the top.", "Ribs down, no lower-back arch."],
  "Smith machine incline press": ["Upper chest and front delts.", "Shoulder blades squeezed; the bar comes down to your upper chest."],
  "Barbell overhead press": ["Shoulders, triceps and core.", "Glutes and abs braced, no leaning back through your lower back."],
  "DB wrist curl": ["Flexors on the inner forearm.", "Move only at the wrist; your forearm rests on the bench."],
  "DB reverse wrist curl": ["Extensors on the outer forearm.", "Light weight; pain near the elbow = reduce the weight or shorten the range."],
  "Cable reverse curl": ["Brachioradialis and outer forearm.", "Elbows at your sides, wrists straight."],
  "DB shrug": ["Upper traps – shoulders up toward your ears, hold at the top.", "Don't roll your shoulders; neck relaxed."],
  "Barbell shrug": ["Upper traps.", "Arms straight, don't pull with your arms; don't roll your shoulders."],
  "Smith machine shrug": ["Upper traps.", "Shoulders straight up and down; head in line with your spine."],
  "Cable upright row": ["Traps and side delts.", "Elbows no higher than shoulder height; sharp shoulder pain = stop lower or use a wider grip."],
  "Barbell good morning": ["Hamstrings and glutes; your lower back holds a neutral spine.", "Never round your back; start light and go only until you feel a hamstring stretch."]
};
